### ISSUE TITLE
Live demos don't work on multiple browsers

### ISSUE THREAD

**Issue by BrandtM** [stasilo/retrace.gl#1]
Tested with Firefox 67.0.2 and Chrome 76.0.3809.12.  
Firefox console prints out:  
`es6.promise.js:110  Unhandled promise rejection TypeError: "this.uniforms[e] is undefined"`  
And Chrome prints:  
`picogl.js:3928  Uncaught (in promise) TypeError: Cannot read property 'set' of undefined`  

Despite the different error messages both browsers deliver an identical page. It's completely black but the menu as well as the code editor are visible.

**Comment by stasilo** [comment]
I think this should be resolved in the new version with sdf support. Closing for now.

**Comment by MaxBittker** [comment]
Sorry if it's obnoxious to follow up so quickly, but I don't think the live demo build has been updated to reflect this fix (I still get this error).

retrace seems really cool and I'm excited to try it out! I've written a lot of SDFs in the past, never with tooling 1/10 as nice as this :)

**Comment by stasilo** [comment]
@MaxBittker No, not at all! :) It's a bit hard for me to debug this though, as all scenes work perfectly for me on my os x setup with the latest versions of Chrome & Firefox.

**Comment by stasilo** [comment]
@MaxBittker No, not at all, and thanks :) It's a bit hard for me to debug this though, as all scenes work perfectly for me on both my home & work mac os setups running the latest/almost latest versions of chrome & firefox. 

Do you experience the same issue with all scenes? Could you provide some info on your environment? (os, browser, screen resolution, gpu & gpu driver details would be fantastic). 

I recognise this error string, though. For me it usually has appeared after the webgl context has been lost at one point (i.e. webgl has crashed), in which case a browser restart fixes it for me. That'd be the first thing I'd try :) 

Or, you're running Windows and are experiencing loooong shader compilation times (and probably other issues) due to ANGLE, which can cause context loss/a webgl crash. In which case there isn't much to do I think (you should still be able to run most demos with the sdf render mode, though).

**Comment by MaxBittker** [comment]
linux, chrome, 2560 x 1440
![0HSoFAZw3ZL](https://user-images.githubusercontent.com/5915546/75296465-1d0f7880-57e2-11ea-8e3b-647365ae91f7.png)


the problem is the same in the scene links i tried from the readme, and persisted since I restarted my browser

I haven't tried cloning and building locally, maybe it's just that the new version hasn't been regenerated for gh-pages?
